<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="14.0.0" />
    <PackageReference Include="AWSSDK.Core" Version="4.0.0.6" />
    <PackageReference Include="MediatR" Version="12.5.0" />
    <PackageReference Include="Moq.Dapper" Version="1.0.7" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Newtonsoft.Json.Bson" Version="1.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="8.1.2" />
    <PackageReference Include="System.Text.Json" Version="4.7.2" />
  </ItemGroup>

</Project>
